### PR TITLE
Add missing colors, images and fix dates

### PR DESCRIPTION
**Pull request by phimage**
Add env property PROJECT_DIR in test to be able to find file because #file not working anymore well with SwiftPM
Fix stepper date

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
Please use #filePath instead of #file in Swift 5.3

**Comment by phimage** [comment]
yes I see on internet but have not updated my Xcode yet. I suppose filePath not available before

**Comment by phimage** [comment]
tested  file:///private/tmp/ with Xcode 12
#filePath is also file:///private/tmp/

in code 
```swift
 #if swift(>=5.3)
            var resourcesURL = URL(fileURLWithPath: #filePath).deletingLastPathComponent().appendingPathComponent("Resources")
            #else
            var resourcesURL = URL(fileURLWithPath: #file).deletingLastPathComponent().appendingPathComponent("Resources")
            #endif
```
and also updating Package.swift to set 5.3

**Comment by phimage** [comment]
I create an issue #81 for this test issue so I could merge and we do not loose the task

**Pull request merged**
