### PR TITLE
Add missing connection models

### PR DESCRIPTION
**Pull request by kateinoigakukun**
- Add Action
- Add OutletCollection
- Parse all connection in document
 - This is temporary implementation until all connections are parsed correctly. (ex. gesture recognizer or unsupported views)

### CODE REVIEW

**Comment by phimage** [comment]
Ok for the objects

I am just wondering about the list of connexion in storyboard.
Is it to implement an iblinter rule that you need a global list? Or just because there is some issue and as you say this is temporary

**Comment by kateinoigakukun** [comment]
I’ll implement an rule that checks connections between swift code and interface builder and needs all connections list.

**Comment by phimage** [comment]
ok, that's what I thought, because I am thinking about some rules to implement.

Some other rules will need all objects by `id` in a dictionary, others by type (xml element name)
So we need some indexes, or way to find id.
(xcode project format, pbxproj file, index all objects natively like that)

There is many way to do it.
- A visitor pattern, each objects must provide its list of children, then the visitor could browse the tree.
- A listener, each object send a notification at creation
- A protocol in parser, like a delegate, which is passed in init
- ...

So by providing a visitor I think if a rule need it, we can look for one object, or one type of object, etc.. And to speed up we can provide a cache, an index on some criteria like id or type

**Comment by SD10** [comment]
> A visitor pattern, each objects must provide its list of children, then the visitor could browse the tree.

I think this is the best approach.

I just want to mention that it was my plan to design IBDecodable to be independent of any IBLinter logic. The goal of IBDecodable is just to parse as much information from Storyboard XML as possible so that it can be used for other tools unrelated to IBLinter. 

If further processing needs to be done on that information, I believe it should be done in IBLinter. Just keep that in mind, please 👍

**Pull request merged**
